test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -36,8 +36,8 @@ jobs:
               major) ((major_count++));;
             esac 
           done
-          
-         if [[ "$minor_count+bug_count+major_count == 1 ]]; then 
+
+          if [[ "$minor_count+bug_count+major_count == 1 ]]; then 
         
            if [ "$minor_count == 1 ]; then 
              echo "::set-output name=label_type::minor"
@@ -49,8 +49,8 @@ jobs:
             echo "::set-output name=label_type::major"
             echo "::debug::Label 'major' found!"
            fi
-         else 
-          echo "Label field1 not found." 
-          exit 1  # 终止 Workflow 并标记为失败
-         fi
+           else 
+            echo "Label field1 not found." 
+            exit 1  # 终止 Workflow 并标记为失败
+          fi
           
